import Mathlib.MeasureTheory.MeasurableSpace.Defs

/-!
# Absorption oracle: measurable-space construction

This file formalises the well-definedness lemma for the final-observation
absorption oracle.  The observed persistence events are denoted by `E k`, and
`f` is the realised final observation stage.  The event revealed by the oracle
is

`⋃ k, E k ∩ {ω | f ω = k}`.

The enlargement is characterised by its universal property: it is the
smallest measurable space containing the original information and making the
absorption event measurable.
-/

namespace SequentialLearning

open Set MeasurableSpace
open scoped MeasureTheory

section AbsorptionOracle

variable {Ω : Type*}

/-- The event that persistence has occurred by the realised final observation
stage. -/
def absorptionEvent (E : ℕ → Set Ω) (f : Ω → ℕ) : Set Ω :=
  ⋃ k, E k ∩ {ω | f ω = k}

/-- The absorption event is measurable whenever each persistence event and
each final-stage fibre are measurable.  Fibre measurability is the exact
property of `f` used by the argument. -/
theorem measurableSet_absorptionEvent [MeasurableSpace Ω]
    (E : ℕ → Set Ω) (f : Ω → ℕ)
    (hE : ∀ k, MeasurableSet (E k))
    (hf : ∀ k, MeasurableSet {ω | f ω = k}) :
    MeasurableSet (absorptionEvent E f) := by
  exact MeasurableSet.iUnion fun k => (hE k).inter (hf k)

/-- The measurable space generated by one event. -/
@[instance_reducible]
def generatedByEvent (A : Set Ω) : MeasurableSpace Ω :=
  generateFrom {A}

/-- Its generating event is measurable. -/
theorem measurableSet_generatedByEvent (A : Set Ω) :
    MeasurableSet[generatedByEvent A] A := by
  exact measurableSet_generateFrom (by simp)

/-- The measurable space generated by `A` is the smallest one in which `A` is
measurable. -/
theorem generatedByEvent_le {A : Set Ω} {m : MeasurableSpace Ω}
    (hA : MeasurableSet[m] A) :
    generatedByEvent A ≤ m := by
  unfold generatedByEvent
  refine generateFrom_le ?_
  intro s hs
  rcases hs with rfl
  exact hA

/-- Enlarge the terminal observed information by the single absorption-status
event. -/
@[instance_reducible]
def absorptionOracleMeasurableSpace
    (FInf : MeasurableSpace Ω) (A : Set Ω) : MeasurableSpace Ω :=
  FInf ⊔ generatedByEvent A

/-- The oracle enlargement retains every event in the original information. -/
theorem le_absorptionOracleMeasurableSpace
    (FInf : MeasurableSpace Ω) (A : Set Ω) :
    FInf ≤ absorptionOracleMeasurableSpace FInf A := by
  exact le_sup_left

/-- The oracle enlargement resolves the absorption event. -/
theorem measurableSet_absorptionOracle
    (FInf : MeasurableSpace Ω) (A : Set Ω) :
    MeasurableSet[absorptionOracleMeasurableSpace FInf A] A := by
  have hle : generatedByEvent A ≤
      absorptionOracleMeasurableSpace FInf A := le_sup_right
  exact hle A (measurableSet_generatedByEvent A)

/-- Universal property of the oracle enlargement: any measurable space that
contains `F∞` and resolves `A` also contains the oracle enlargement. -/
theorem absorptionOracleMeasurableSpace_le
    {FInf m : MeasurableSpace Ω} {A : Set Ω}
    (hFInf : FInf ≤ m) (hA : MeasurableSet[m] A) :
    absorptionOracleMeasurableSpace FInf A ≤ m := by
  exact sup_le hFInf (generatedByEvent_le hA)

/-- Full well-definedness statement for the final-observation absorption
oracle, including ambient measurability and the precise minimality claim. -/
theorem absorption_oracle_well_defined [MeasurableSpace Ω]
    (FInf : MeasurableSpace Ω) (E : ℕ → Set Ω) (f : Ω → ℕ)
    (hFInf : FInf ≤ (inferInstance : MeasurableSpace Ω))
    (hE : ∀ k, MeasurableSet (E k))
    (hf : ∀ k, MeasurableSet {ω | f ω = k}) :
    let A := absorptionEvent E f
    MeasurableSet A ∧
      FInf ≤ absorptionOracleMeasurableSpace FInf A ∧
      MeasurableSet[absorptionOracleMeasurableSpace FInf A] A ∧
      absorptionOracleMeasurableSpace FInf A ≤
        (inferInstance : MeasurableSpace Ω) ∧
      ∀ m : MeasurableSpace Ω,
        FInf ≤ m → MeasurableSet[m] A →
          absorptionOracleMeasurableSpace FInf A ≤ m := by
  dsimp only
  have hA : MeasurableSet (absorptionEvent E f) :=
    measurableSet_absorptionEvent E f hE hf
  refine ⟨hA, le_absorptionOracleMeasurableSpace _ _,
    measurableSet_absorptionOracle _ _, ?_, ?_⟩
  · exact absorptionOracleMeasurableSpace_le hFInf hA
  · intro m hm hmA
    exact absorptionOracleMeasurableSpace_le hm hmA

end AbsorptionOracle

end SequentialLearning
