import SequentialLearning.HilbertLearningCriterion
import Mathlib.Probability.Martingale.Convergence

set_option maxHeartbeats 800000

open Filter MeasureTheory ProbabilityTheory Set Topology
open scoped ENNReal MeasureTheory ProbabilityTheory RealInnerProductSpace

namespace SequentialLearning

noncomputable section

variable {Omega : Type*} {mOmega : MeasurableSpace Omega}

/-- Sigma-algebra generated by all finite stages of a filtration. -/
def filtrationLimit (filtration : Filtration ℕ mOmega) :
    MeasurableSpace Omega :=
  ⨆ n, filtration n

theorem filtration_le_limit (filtration : Filtration ℕ mOmega) (n : ℕ) :
    filtration n ≤ filtrationLimit filtration :=
  le_iSup filtration n

theorem filtrationLimit_le_ambient (filtration : Filtration ℕ mOmega) :
    filtrationLimit filtration ≤ mOmega :=
  iSup_le fun n => filtration.le n

theorem scalar_indicator_mem_filtrationL2_closure
    (mu : Measure[mOmega] Omega) [IsProbabilityMeasure mu]
    (filtration : Filtration ℕ mOmega)
    (s : Set Omega) (hs : MeasurableSet[filtrationLimit filtration] s) :
    let U : ℕ → Submodule ℝ (Omega →₂[mu] ℝ) :=
      fun n => lpMeas ℝ ℝ (filtration n) 2 mu
    let f : Omega →₂[mu] ℝ := indicatorConstLp 2
      (filtrationLimit_le_ambient filtration s hs) (measure_ne_top mu s) 1
    f ∈ (⨆ n, U n).topologicalClosure := by
  dsimp only
  let U : ℕ → Submodule ℝ (Omega →₂[mu] ℝ) :=
    fun n => lpMeas ℝ ℝ (filtration n) 2 mu
  let f : Omega →₂[mu] ℝ := indicatorConstLp 2
    (filtrationLimit_le_ambient filtration s hs) (measure_ne_top mu s) 1
  have hU : Monotone U := by
    intro i j hij g hg
    rw [mem_lpMeas_iff_aestronglyMeasurable] at hg ⊢
    exact hg.mono (filtration.mono hij)
  letI : ∀ n, Fact (filtration n ≤ mOmega) := fun n => ⟨filtration.le n⟩
  have hStar := Submodule.starProjection_tendsto_closure_iSup U hU f
  let y : Omega →₂[mu] ℝ :=
    (⨆ n, U n).topologicalClosure.starProjection f
  have hStar' : Tendsto (fun n => (U n).starProjection f) atTop (nhds y) := by
    exact hStar
  have hInMeasureY : TendstoInMeasure mu
      (fun n omega => ((U n).starProjection f : Omega → ℝ) omega)
      atTop (fun omega => y omega) :=
    tendstoInMeasure_of_tendsto_Lp hStar'
  have hFmem : f ∈ lpMeas ℝ ℝ (filtrationLimit filtration) 2 mu := by
    exact mem_lpMeas_indicatorConstLp
      (filtrationLimit_le_ambient filtration) hs (measure_ne_top mu s)
  have hFMeas : AEStronglyMeasurable[filtrationLimit filtration]
      (fun omega => f omega) mu :=
    (mem_lpMeas_iff_aestronglyMeasurable.mp hFmem)
  have hFInt : Integrable (fun omega => f omega) mu :=
    (Lp.memLp f).integrable (by norm_num)
  have hLimitCond :
      mu[(fun omega => f omega) | filtrationLimit filtration] =ᵐ[mu]
        fun omega => f omega :=
    condExp_of_aestronglyMeasurable'
      (filtrationLimit_le_ambient filtration) hFMeas hFInt
  have hLevyRaw := MeasureTheory.tendsto_ae_condExp
    (μ := mu) (ℱ := filtration) (fun omega => f omega)
  have hLevy : ∀ᵐ omega ∂mu, Tendsto
      (fun n => mu[(fun a => f a) | filtration n] omega)
      atTop (nhds (f omega)) := by
    filter_upwards [hLevyRaw, hLimitCond] with omega hOmega hLimitOmega
    rw [← hLimitOmega]
    simpa only [filtrationLimit] using hOmega
  have hCondEq : ∀ n,
      (fun omega => ((U n).starProjection f : Omega → ℝ) omega) =ᵐ[mu]
        mu[(fun omega => f omega) | filtration n] := by
    intro n
    have hToLp : (Lp.memLp f).toLp (fun omega => f omega) = f := by
      apply Lp.ext
      exact (Lp.memLp f).coeFn_toLp
    have hCond := (Lp.memLp f).condExpL2_ae_eq_condExp
      (𝕜 := ℝ) (filtration.le n)
    rw [hToLp] at hCond
    simpa only [U, Submodule.starProjection, condExpL2,
      ContinuousLinearMap.comp_apply, Submodule.subtypeL_apply] using hCond
  have hInMeasureF : TendstoInMeasure mu
      (fun n omega => ((U n).starProjection f : Omega → ℝ) omega)
      atTop (fun omega => f omega) := by
    have hRaw : TendstoInMeasure mu
        (fun n => mu[(fun omega => f omega) | filtration n])
        atTop (fun omega => f omega) :=
      tendstoInMeasure_of_tendsto_ae
      (fun n => by
        have hMeas : StronglyMeasurable[filtration n]
            mu[(fun omega => f omega) | filtration n] :=
          stronglyMeasurable_condExp
        exact (hMeas.mono (filtration.le n)).aestronglyMeasurable)
      hLevy
    exact TendstoInMeasure.congr
      (f := fun n => mu[(fun omega => f omega) | filtration n])
      (f' := fun n omega => ((U n).starProjection f : Omega → ℝ) omega)
      (g := fun omega => f omega) (g' := fun omega => f omega)
      (fun n => (hCondEq n).symm) EventuallyEq.rfl hRaw
  have hyf : (fun omega => y omega) =ᵐ[mu] fun omega => f omega :=
    tendstoInMeasure_ae_unique hInMeasureY hInMeasureF
  have hyfLp : y = f := by
    apply Lp.ext
    exact hyf
  change f ∈ (⨆ n, U n).topologicalClosure
  rw [← hyfLp]
  exact Submodule.coe_mem _

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H]
  [CompleteSpace H]

theorem hilbert_indicator_mem_filtrationL2_closure
    (mu : Measure[mOmega] Omega) [IsProbabilityMeasure mu]
    (filtration : Filtration ℕ mOmega)
    (s : Set Omega) (hs : MeasurableSet[filtrationLimit filtration] s)
    (c : H) :
    indicatorConstLp 2 (filtrationLimit_le_ambient filtration s hs)
        (measure_ne_top mu s) c ∈
      (⨆ n, lpMeas H ℝ (filtration n) 2 mu).topologicalClosure := by
  let US : ℕ → Submodule ℝ (Omega →₂[mu] ℝ) :=
    fun n => lpMeas ℝ ℝ (filtration n) 2 mu
  let UH : ℕ → Submodule ℝ (Omega →₂[mu] H) :=
    fun n => lpMeas H ℝ (filtration n) 2 mu
  let fScalar : Omega →₂[mu] ℝ := indicatorConstLp 2
    (filtrationLimit_le_ambient filtration s hs) (measure_ne_top mu s) 1
  let fHilbert : Omega →₂[mu] H := indicatorConstLp 2
    (filtrationLimit_le_ambient filtration s hs) (measure_ne_top mu s) c
  let C : (Omega →₂[mu] ℝ) →L[ℝ] (Omega →₂[mu] H) :=
    (ContinuousLinearMap.toSpanSingleton ℝ c).compLpL 2 mu
  have hScalar : fScalar ∈ (⨆ n, US n).topologicalClosure := by
    exact scalar_indicator_mem_filtrationL2_closure mu filtration s hs
  have hMapStage : ∀ n, (US n).map C.toLinearMap ≤ UH n := by
    intro n g hg
    rcases hg with ⟨g, hg, rfl⟩
    change g ∈ lpMeas ℝ ℝ (filtration n) 2 mu at hg
    change C g ∈ lpMeas H ℝ (filtration n) 2 mu
    rw [mem_lpMeas_iff_aestronglyMeasurable] at hg ⊢
    have hComp : AEStronglyMeasurable[filtration n]
        (fun omega => (ContinuousLinearMap.toSpanSingleton ℝ c) (g omega)) mu :=
      (ContinuousLinearMap.toSpanSingleton ℝ c).cont.comp_aestronglyMeasurable hg
    have hCoe :
        (fun omega => (ContinuousLinearMap.toSpanSingleton ℝ c) (g omega))
            =ᵐ[mu]
          fun omega => C g omega := by
      have h := (ContinuousLinearMap.toSpanSingleton ℝ c).coeFn_compLp g
      filter_upwards [h] with omega hOmega
      change (ContinuousLinearMap.toSpanSingleton ℝ c) (g omega) =
        ((ContinuousLinearMap.toSpanSingleton ℝ c).compLp g) omega
      exact hOmega.symm
    exact hComp.congr hCoe
  have hMapSup : (⨆ n, US n).map C.toLinearMap ≤ ⨆ n, UH n := by
    rw [Submodule.map_iSup]
    exact iSup_mono hMapStage
  have hMappedClosure : C fScalar ∈
      ((⨆ n, US n).map C.toLinearMap).topologicalClosure := by
    exact (Submodule.topologicalClosure_map C (⨆ n, US n))
      ⟨fScalar, hScalar, rfl⟩
  have hTarget : C fScalar ∈ (⨆ n, UH n).topologicalClosure :=
    Submodule.topologicalClosure_mono hMapSup hMappedClosure
  have hCH : C fScalar = fHilbert := by
    change (ContinuousLinearMap.toSpanSingleton ℝ c).compLp fScalar =
      fHilbert
    simpa only [C, fScalar, fHilbert] using
      (indicatorConstLp_eq_toSpanSingleton_compLp
        (filtrationLimit_le_ambient filtration s hs)
        (measure_ne_top mu s) c).symm
  change fHilbert ∈ (⨆ n, UH n).topologicalClosure
  rw [← hCH]
  exact hTarget

theorem filtrationL2_closure_eq_limit
    (mu : Measure[mOmega] Omega) [IsProbabilityMeasure mu]
    (filtration : Filtration ℕ mOmega) :
    (⨆ n, lpMeas H ℝ (filtration n) 2 mu).topologicalClosure =
      lpMeas H ℝ (filtrationLimit filtration) 2 mu := by
  apply le_antisymm
  · apply Submodule.topologicalClosure_minimal
    · apply iSup_le
      intro n g hg
      rw [mem_lpMeas_iff_aestronglyMeasurable] at hg ⊢
      exact hg.mono (filtration_le_limit filtration n)
    · have hClosed := isClosed_aestronglyMeasurable
        (F := H) (p := (2 : ℝ≥0∞)) (μ := mu)
        (filtrationLimit_le_ambient filtration)
      convert hClosed using 1
      ext g
      exact mem_lpMeas_iff_aestronglyMeasurable
  · intro f hf
    rw [mem_lpMeas_iff_aestronglyMeasurable] at hf
    apply Lp.induction_stronglyMeasurable_aux
      (F := H) (p := (2 : ℝ≥0∞))
      (filtrationLimit_le_ambient filtration) (by norm_num)
      (fun g => g ∈ (⨆ n, lpMeas H ℝ (filtration n) 2 mu).topologicalClosure)
    · intro c s hs hmus
      simpa only [Lp.simpleFunc.coe_indicatorConst] using
        hilbert_indicator_mem_filtrationL2_closure mu filtration s hs c
    · intro f g hfInt hgInt hfMeas hgMeas hDisjoint hfMem hgMem
      exact Submodule.add_mem _ hfMem hgMem
    · have hClosed := Submodule.isClosed_topologicalClosure
        (⨆ n, lpMeas H ℝ (filtration n) 2 mu)
      exact hClosed.preimage continuous_subtype_val
    · exact hf

theorem hilbert_condExpL2_tendsto_filtrationLimit
    (mu : Measure[mOmega] Omega) [IsProbabilityMeasure mu]
    (filtration : Filtration ℕ mOmega)
    (K : Omega → H) (hK : MemLp K 2 mu) :
    Tendsto
      (fun n => ((condExpL2 H ℝ (filtration.le n)) (hK.toLp K) :
        Omega →₂[mu] H))
      atTop
      (nhds ((condExpL2 H ℝ (filtrationLimit_le_ambient filtration))
        (hK.toLp K) : Omega →₂[mu] H)) := by
  let U : ℕ → Submodule ℝ (Omega →₂[mu] H) :=
    fun n => lpMeas H ℝ (filtration n) 2 mu
  have hU : Monotone U := by
    intro i j hij g hg
    rw [mem_lpMeas_iff_aestronglyMeasurable] at hg ⊢
    exact hg.mono (filtration.mono hij)
  letI : ∀ n, Fact (filtration n ≤ mOmega) := fun n => ⟨filtration.le n⟩
  letI : Fact (filtrationLimit filtration ≤ mOmega) :=
    ⟨filtrationLimit_le_ambient filtration⟩
  have hStar := Submodule.starProjection_tendsto_closure_iSup U hU (hK.toLp K)
  have hSubspace : (⨆ n, U n).topologicalClosure =
      lpMeas H ℝ (filtrationLimit filtration) 2 mu := by
    simpa only [U] using filtrationL2_closure_eq_limit
      (H := H) mu filtration
  have hProjection :
      (⨆ n, U n).topologicalClosure.starProjection (hK.toLp K) =
        (lpMeas H ℝ (filtrationLimit filtration) 2 mu).starProjection
          (hK.toLp K) := by
    symm
    apply Submodule.eq_starProjection_of_mem_of_inner_eq_zero
    · rw [← hSubspace]
      exact Submodule.coe_mem _
    · intro w hw
      rw [← hSubspace] at hw
      exact (Submodule.mem_orthogonal'
        ((⨆ n, U n).topologicalClosure) _).mp
          (Submodule.sub_starProjection_mem_orthogonal
            (K := (⨆ n, U n).topologicalClosure) (hK.toLp K)) w hw
  rw [hProjection] at hStar
  simpa only [U, Submodule.starProjection, condExpL2,
    ContinuousLinearMap.comp_apply, Submodule.subtypeL_apply] using hStar

theorem L2_norm_sq_eq_integral_norm_sq
    (f : Omega →₂[mu] H) :
    ‖f‖ ^ 2 = ∫ omega, ‖f omega‖ ^ 2 ∂mu := by
  rw [norm_sq_eq_re_inner (𝕜 := ℝ)]
  change inner ℝ f f = _
  rw [L2.inner_def]
  congr with omega
  exact real_inner_self_eq_norm_sq (f omega)

theorem hilbert_posteriorMean_L2_upward
    (mu : Measure[mOmega] Omega) [IsProbabilityMeasure mu]
    (filtration : Filtration ℕ mOmega)
    (K : Omega → H) (hK : MemLp K 2 mu) :
    Tendsto
      (fun n => ∫ omega,
        ‖posteriorMean mu (filtrationLimit filtration) K omega -
          posteriorMean mu (filtration n) K omega‖ ^ 2 ∂mu)
      atTop (nhds 0) := by
  let M : ℕ → (Omega →₂[mu] H) := fun n =>
    (condExpL2 H ℝ (filtration.le n)) (hK.toLp K)
  let MLimit : Omega →₂[mu] H :=
    (condExpL2 H ℝ (filtrationLimit_le_ambient filtration)) (hK.toLp K)
  have hLp : Tendsto M atTop (nhds MLimit) := by
    exact hilbert_condExpL2_tendsto_filtrationLimit mu filtration K hK
  have hDiff : Tendsto (fun n => MLimit - M n) atTop (nhds 0) := by
    convert tendsto_const_nhds.sub hLp using 1 <;> simp
  have hNorm : Tendsto (fun n => ‖MLimit - M n‖) atTop (nhds 0) := by
    have h := (continuous_norm.tendsto 0).comp hDiff
    change Tendsto (fun n => ‖MLimit - M n‖) atTop (nhds ‖(0 :
      Omega →₂[mu] H)‖) at h
    simpa using h
  have hNormSq : Tendsto (fun n => ‖MLimit - M n‖ ^ 2)
      atTop (nhds 0) := by
    simpa using hNorm.pow 2
  have hCondLimit : (fun omega => MLimit omega) =ᵐ[mu]
      posteriorMean mu (filtrationLimit filtration) K := by
    exact hK.condExpL2_ae_eq_condExp (𝕜 := ℝ)
      (filtrationLimit_le_ambient filtration)
  have hCond : ∀ n, (fun omega => M n omega) =ᵐ[mu]
      posteriorMean mu (filtration n) K := by
    intro n
    exact hK.condExpL2_ae_eq_condExp (𝕜 := ℝ) (filtration.le n)
  have hIntegralEq : ∀ n,
      ∫ omega,
          ‖posteriorMean mu (filtrationLimit filtration) K omega -
            posteriorMean mu (filtration n) K omega‖ ^ 2 ∂mu =
        ‖MLimit - M n‖ ^ 2 := by
    intro n
    have hCoeSub : (fun omega => (MLimit - M n) omega) =ᵐ[mu]
        fun omega =>
          posteriorMean mu (filtrationLimit filtration) K omega -
            posteriorMean mu (filtration n) K omega := by
      filter_upwards [Lp.coeFn_sub MLimit (M n), hCondLimit, hCond n]
        with omega hSub hLimit hn
      rw [hSub]
      change MLimit omega - M n omega =
        posteriorMean mu (filtrationLimit filtration) K omega -
          posteriorMean mu (filtration n) K omega
      rw [hLimit, hn]
    calc
      ∫ omega,
          ‖posteriorMean mu (filtrationLimit filtration) K omega -
            posteriorMean mu (filtration n) K omega‖ ^ 2 ∂mu =
          ∫ omega, ‖(MLimit - M n) omega‖ ^ 2 ∂mu := by
            apply integral_congr_ae
            filter_upwards [hCoeSub] with omega hOmega
            rw [hOmega]
      _ = ‖MLimit - M n‖ ^ 2 :=
        (L2_norm_sq_eq_integral_norm_sq (mu := mu) (MLimit - M n)).symm
  simpa only [hIntegralEq] using hNormSq

end

end SequentialLearning
