import Mathlib.Probability.UniformOn
import Mathlib.Probability.Process.Filtration
import Mathlib.Tactic.FinCases
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.Order

/-!
# A finite two-signal observation model

The latent space has 256 equiprobable states.  The first sign has crossover
probability `q = 1/4`; the second has crossover probability `q' = 7/16`.
The observation filtration reveals no sign, then the first sign, then both.
Closed rational posterior-variance calculations are checked by the kernel.
-/

namespace SequentialLearning

open MeasureTheory ProbabilityTheory Set
open scoped BigOperators ENNReal MeasureTheory ProbabilityTheory

noncomputable section

namespace NoisyObservationModel

/-- Eight finite bits' worth of latent data: the hidden sign, two error
selectors of sizes four and sixteen, and a spare branch bit for the structural
flag process. -/
structure LatentState where
  truth : Bool
  noise1 : Fin 4
  noise2 : Fin 16
  branch : Bool
  deriving DecidableEq, Fintype, Inhabited

instance : MeasurableSpace LatentState := ⊤

set_option maxRecDepth 100000 in
theorem card_latentState : Fintype.card LatentState = 256 := by decide

/-- The uniform probability law on all 256 latent states. -/
def latentLaw : Measure LatentState := uniformOn Set.univ

instance : IsProbabilityMeasure latentLaw := by
  dsimp [latentLaw]
  infer_instance

/-- The first channel flips exactly one of the four error-selector values. -/
def firstSignal (omega : LatentState) : Bool :=
  if omega.noise1 = 0 then !omega.truth else omega.truth

/-- The second channel flips exactly seven of the sixteen selector values. -/
def secondSignal (omega : LatentState) : Bool :=
  if omega.noise2.val < 7 then !omega.truth else omega.truth

def noObservation (_ : LatentState) : Unit := ()
def oneObservation (omega : LatentState) : Bool := firstSignal omega
def twoObservations (omega : LatentState) : Bool × Bool :=
  (firstSignal omega, secondSignal omega)

/-- Sigma algebras generated by zero, one, and two observed signs. -/
def generatedZero : MeasurableSpace LatentState := ⊥
def generatedOne : MeasurableSpace LatentState :=
  MeasurableSpace.comap oneObservation ⊤
def generatedTwo : MeasurableSpace LatentState :=
  MeasurableSpace.comap twoObservations ⊤

theorem generatedOne_le_generatedTwo : generatedOne ≤ generatedTwo := by
  have hfst : @Measurable (Bool × Bool) Bool ⊤ ⊤ Prod.fst :=
    measurable_from_top
  exact MeasurableSpace.comap_le_comap_of_eq_comp Prod.fst hfst rfl

/-- The three-stage generated observation filtration. -/
def observationSpace (n : Fin 3) : MeasurableSpace LatentState :=
  if n.val = 0 then generatedZero
  else if n.val = 1 then generatedOne
  else generatedTwo

theorem observationSpace_monotone : Monotone observationSpace := by
  intro i j hij
  fin_cases i <;> fin_cases j <;> simp [observationSpace] at hij ⊢
  · exact bot_le
  · exact bot_le
  · exact generatedOne_le_generatedTwo

def filtration : Filtration (Fin 3) (⊤ : MeasurableSpace LatentState) where
  seq := observationSpace
  mono' := observationSpace_monotone
  le' := fun _ => le_top

@[simp] theorem filtration_zero : filtration 0 = generatedZero := by
  rfl

@[simp] theorem filtration_one : filtration 1 = generatedOne := by
  rfl

@[simp] theorem filtration_two : filtration 2 = generatedTwo := by
  rfl

/-- First and second binary-symmetric-channel crossover probabilities. -/
def q : ℚ := 1 / 4
def q' : ℚ := 7 / 16

def sign : Bool → ℚ
  | false => -1
  | true => 1

def likelihood (error : ℚ) (theta observed : Bool) : ℚ :=
  if theta = observed then 1 - error else error

def priorWeight (_ : Bool) : ℚ := 1 / 2

def evidenceOne (observed : Bool) : ℚ :=
  ∑ theta : Bool, priorWeight theta * likelihood q theta observed

def posteriorMeanOne (observed : Bool) : ℚ :=
  (∑ theta : Bool,
      sign theta * priorWeight theta * likelihood q theta observed) /
    evidenceOne observed

def posteriorVarianceOne (observed : Bool) : ℚ :=
  1 - posteriorMeanOne observed ^ 2

def evidenceTwo (observed1 observed2 : Bool) : ℚ :=
  ∑ theta : Bool, priorWeight theta * likelihood q theta observed1 *
    likelihood q' theta observed2

def posteriorMeanTwo (observed1 observed2 : Bool) : ℚ :=
  (∑ theta : Bool,
      sign theta * priorWeight theta * likelihood q theta observed1 *
        likelihood q' theta observed2) /
    evidenceTwo observed1 observed2

def posteriorVarianceTwo (observed1 observed2 : Bool) : ℚ :=
  1 - posteriorMeanTwo observed1 observed2 ^ 2

def priorVariance : ℚ := 1

def expectedVarianceOne : ℚ :=
  ∑ observed : Bool, evidenceOne observed * posteriorVarianceOne observed

def expectedVarianceTwo : ℚ :=
  ∑ observed1 : Bool, ∑ observed2 : Bool,
    evidenceTwo observed1 observed2 * posteriorVarianceTwo observed1 observed2

theorem priorVariance_eq : priorVariance = 1 := rfl

theorem posteriorVarianceOne_eq (observed : Bool) :
    posteriorVarianceOne observed = 3 / 4 := by
  cases observed <;>
    norm_num [posteriorVarianceOne, posteriorMeanOne, evidenceOne,
      priorWeight, likelihood, sign, q]

theorem posteriorVarianceTwo_agree_false :
    posteriorVarianceTwo false false = 189 / 289 := by
  norm_num [posteriorVarianceTwo, posteriorMeanTwo, evidenceTwo,
    priorWeight, likelihood, sign, q, q']

theorem posteriorVarianceTwo_disagree :
    posteriorVarianceTwo false true = 21 / 25 := by
  norm_num [posteriorVarianceTwo, posteriorMeanTwo, evidenceTwo,
    priorWeight, likelihood, sign, q, q']

theorem posteriorVarianceTwo_agree_true :
    posteriorVarianceTwo true true = 189 / 289 := by
  norm_num [posteriorVarianceTwo, posteriorMeanTwo, evidenceTwo,
    priorWeight, likelihood, sign, q, q']

theorem expectedVarianceOne_eq : expectedVarianceOne = 3 / 4 := by
  norm_num [expectedVarianceOne, posteriorVarianceOne, posteriorMeanOne,
    evidenceOne, priorWeight, likelihood, sign, q]

theorem expectedVarianceTwo_eq : expectedVarianceTwo = 63 / 85 := by
  norm_num [expectedVarianceTwo, posteriorVarianceTwo, posteriorMeanTwo,
    evidenceTwo, priorWeight, likelihood, sign, q, q']

/-- The second observation gives both realised verdicts.  Agreement lowers
posterior variance, disagreement raises it, even though the expected posterior
variance falls from `3/4` to `63/85`. -/
theorem both_verdicts :
    posteriorVarianceTwo false false < posteriorVarianceOne false ∧
      posteriorVarianceOne false < posteriorVarianceTwo false true ∧
      expectedVarianceTwo < expectedVarianceOne := by
  rw [posteriorVarianceTwo_agree_false, posteriorVarianceOne_eq,
    posteriorVarianceTwo_disagree, expectedVarianceTwo_eq,
    expectedVarianceOne_eq]
  norm_num

end NoisyObservationModel

end

end SequentialLearning
